src/WixToolset.Core/Compiler.cs
=> Prevent crash when non-advertised Class omits Context. Fixes #5651.

src/WixToolset.Core/ExtensibilityServices/PreprocessHelper.cs, src/test/WixToolsetTest.CoreIntegration/PreprocessorFixture.cs, src/test/WixToolsetTest.CoreIntegration/TestData/Variables/Package.en-us.wxl, src/test/WixToolsetTest.CoreIntegration/TestData/Variables/Package.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/Variables/PackageComponents.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/Variables/data/test.txt, src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
=> Warn on variable redefinition only when the values are different.

src/WixToolset.Core/Compiler.cs
=> Remove context from generated DefaultIcon registry row

src/WixToolset.Core.WindowsInstaller/Decompile/DecompileMsiOrMsmCommand.cs, src/WixToolset.Core.WindowsInstaller/Unbind/ExtractCabinetsCommand.cs
...to support extracting cabinets to the root of the export directory
rather than requiring files in cabinets to be extracted to their own
directory.
=> Clean and create export directory early.

src/WixToolset.Core/CommandLine/BuildCommand.cs, src/WixToolset.Core/ExtensibilityServices/TupleDefinitionCreator.cs, src/test/WixToolsetTest.CoreIntegration/TestData/ComplexExampleExtension/OtherComponents.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/ComplexExampleExtension/Package.en-us.wxl, src/test/WixToolsetTest.CoreIntegration/TestData/ComplexExampleExtension/Package.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/ComplexExampleExtension/PackageComponents.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/ComplexExampleExtension/data/example.txt, src/test/WixToolsetTest.CoreIntegration/TestData/ComplexExampleExtension/data/other.txt, src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj, src/test/WixToolsetTest.CoreIntegration/WixlibFixture.cs
Using a single creator ensures definitions are shared and consistent
across the entire build.
=> Load .wixlib intermediates with single creator

src/WixToolset.Core/CommandLine/BuildCommand.cs, src/WixToolset.Core/CommandLine/CompileCommand.cs, src/WixToolset.Core/IncludedFile.cs, src/WixToolset.Core/PreprocessResult.cs, src/WixToolset.Core/Preprocessor.cs, src/WixToolset.Core/WixToolsetServiceProvider.cs, src/test/WixToolsetTest.CoreIntegration/PreprocessorFixture.cs
This change also cleans up the internal state handling of the preprocesor
to pass the processing state around rather than depend on "global state"
in member variables. This removes the need to "reset" the member
variables before preprocessing which is much cleaner.
=> Include the preprocessed include files with the processed document

src/WixToolset.Core/Compiler.cs, src/test/WixToolsetTest.CoreIntegration/TestData/OverridableActions/Package.wxs
Exposes non-overridable standard actions so WixToolsetTest.CoreIntegration.LinkerFixture.CanBuildWithOverridableActions now fails.
=> Fix missing symbol for WixSuppressAction.

src/test/WixToolsetTest.CoreIntegration/TestData/Wixipl/Package.en-us.wxl, src/test/WixToolsetTest.CoreIntegration/TestData/Wixipl/Package.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/Wixipl/PackageComponents.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/Wixipl/data/test.txt, src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj, src/test/WixToolsetTest.CoreIntegration/WixiplFixture.cs
Add test demonstrating that a persisted .wixipl file has broken
references to bits in an extension's library. Same project built
via wix.exe in one pass works as expected.
=> Bug: Wixipl references to extension libraries

src/test/WixToolsetTest.CoreIntegration/MsiFixture.cs, src/test/WixToolsetTest.CoreIntegration/TestData/ProgId/Package.en-us.wxl, src/test/WixToolsetTest.CoreIntegration/TestData/ProgId/Package.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/ProgId/PackageComponents.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/ProgId/data/test.txt, src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
When a parent ProgId has Advertise="yes" and a child ProgId omits Advertise, the compiler assumes it's a non-advertised ProgId. It should be advertised instead.
=> Add failing test to demonstrate ProgId bug.

src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs, src/test/WixToolsetTest.CoreIntegration/MsiFixture.cs, src/test/WixToolsetTest.CoreIntegration/TestData/ErrorsInUI/Package.en-us.wxl, src/test/WixToolsetTest.CoreIntegration/TestData/ErrorsInUI/Package.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/ErrorsInUI/PackageComponents.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/ErrorsInUI/data/test.txt, src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Strongly-typed tuples are preferred and avoid field-zero/id confusion.
=> Undo CreateTuple change and add ErrorTuple test.

src/WixToolset.Core.Burn/Bundles/ProcessMsiPackageCommand.cs, src/WixToolset.Core/Bind/ResolveDelayedFieldsCommand.cs, src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs, src/test/WixToolsetTest.CoreIntegration/TestData/SimpleBundle/Bundle.wxs
=> Fix resolution of !(bind.ProductVersion.MsiId) bind variables

src/WixToolset.Core/Bind/ResolveFieldsCommand.cs, src/WixToolset.Core/Compiler.cs, src/WixToolset.Core/Librarian.cs, src/WixToolset.Core/VariableResolver.cs, src/test/WixToolsetTest.CoreIntegration/VariableResolverFixture.cs
Handle escaped bind-time variable references.
=> Clean up unused IVariableResolver functionality.

nuget.config, src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs, src/WixToolset.Core.Burn/Bundles/CreateBundleExeCommand.cs, src/WixToolset.Core.Burn/WixToolset.Core.Burn.csproj, src/WixToolset.Core/CommandLine/BuildCommand.cs, src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs, src/test/WixToolsetTest.CoreIntegration/BundleManifestFixture.cs, src/test/WixToolsetTest.CoreIntegration/WixlibFixture.cs
=> Use WixToolset.Burn package to get rid of -burnStubPath

src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs, src/WixToolset.Core.Burn/Bundles/CreateBootstrapperApplicationManifestCommand.cs, src/WixToolset.Core.Burn/Bundles/CreateBurnManifestCommand.cs, src/WixToolset.Core/Compiler_Bundle.cs, src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs, src/test/WixToolsetTest.CoreIntegration/BundleManifestFixture.cs, src/test/WixToolsetTest.CoreIntegration/TestData/BundleCustomTable/BundleCustomTable.wxs, src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Also other fixes needed to test the bundle:
* Process Unreal custom tables in CreateBootstrapperApplicationManifestCommand
* Fix Registration/@ProviderKey in Burn manifest
https://github.com/wixtoolset/issues/issues/6164
=> 6164 - Move DisplayInternalUI into BalExtension

src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs, src/WixToolset.Core.Burn/Bind/GenerateManifestDataFromIRCommand.cs, src/WixToolset.Core.Burn/Bundles/CreateBundleExeCommand.cs, src/WixToolset.Core.Burn/Bundles/CreateNonUXContainers.cs, src/WixToolset.Core/Compiler_Bundle.cs, src/test/Example.Extension/Data/example.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/BundleWithPackageGroupRef/Bundle.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/SimpleBundle/Bundle.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/SimpleBundle/MultiFileBootstrapperApplication.wxs
Core toolset half of https://github.com/wixtoolset/issues/issues/6209
=> 6209 - Use WixBootstrapperApplicationDllSymbol

src/WixToolset.Core/AppCommon.cs
This series of patches enables me to build the `Core` library using .Net Core on Linux (specifically Ubuntu 18.04). See wixtoolset/issues#4381.
=> Linux build fixes

src/WixToolset.Core.TestPackage/WixRunner.cs, src/WixToolset.Core/CommandLine/BuildCommand.cs, src/WixToolset.Core/CommandLine/CommandLineParser.cs, src/WixToolset.Core/Compiler_Bundle.cs, src/test/WixToolsetTest.CoreIntegration/BadInputFixture.cs, src/test/WixToolsetTest.CoreIntegration/BootstrapperApplicationFixture.cs, src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs, src/test/WixToolsetTest.CoreIntegration/ContainerFixture.cs, src/test/WixToolsetTest.CoreIntegration/CustomActionFixture.cs, src/test/WixToolsetTest.CoreIntegration/LinkerFixture.cs, src/test/WixToolsetTest.CoreIntegration/MsiFixture.cs, src/test/WixToolsetTest.CoreIntegration/MsiQueryFixture.cs, src/test/WixToolsetTest.CoreIntegration/MsiTransactionFixture.cs, src/test/WixToolsetTest.CoreIntegration/PayloadFixture.cs, src/test/WixToolsetTest.CoreIntegration/PreprocessorFixture.cs, src/test/WixToolsetTest.CoreIntegration/RegistryFixture.cs, src/test/WixToolsetTest.CoreIntegration/RollbackBoundaryFixture.cs, src/test/WixToolsetTest.CoreIntegration/TestData/BootstrapperApplication/DpiAwareness.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/Container/HarvestIntoDetachedContainer.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/Container/MultipleAttachedContainers.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/Payload/SharedBAAndPackagePayloadBundle.wxs, src/test/WixToolsetTest.CoreIntegration/TestData/RollbackBoundary/BeginningOfChain.wxs, src/test/WixToolsetTest.CoreIntegration/WarningFixture.cs, src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Implement command line for SuppressAllWarnings and WarningsAsError.
Make WixRunner.Execute default to setting WarningsAsError to make sure tests are not accidentally causing warnings.
Fix TryGetNextNonSwitchArgumentOrError.
Fix parsing of DpiAwareness attribute.
https://github.com/wixtoolset/issues/issues/5273
https://github.com/wixtoolset/issues/issues/6144
https://github.com/wixtoolset/issues/issues/6174 (already fixed in v4)
=> Add failing tests

src/WixToolset.Core/Compiler_2.cs, src/test/WixToolsetTest.CoreIntegration/RegistryFixture.cs
=> Removes all trailing backslashes from registry paths.

src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs, src/WixToolset.Core.Burn/Bundles/OrderPackagesAndRollbackBoundariesCommand.cs, src/WixToolset.Core/Compiler_Bundle.cs, src/test/WixToolsetTest.CoreIntegration/RollbackBoundaryFixture.cs
=> Add default rollback boundary in the Burn binder instead of the compiler

src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs, src/WixToolset.Core.Burn/Bind/ResolveDownloadUrlsCommand.cs, src/WixToolset.Core.Burn/Bundles/CreateBurnManifestCommand.cs, src/WixToolset.Core.Burn/BurnBackendErrors.cs, src/test/WixToolsetTest.CoreIntegration/BindVariablesFixture.cs, src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs, src/test/WixToolsetTest.CoreIntegration/PayloadFixture.cs, src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/DuplicateCacheIds.wxs
Resolve container and payload DownloadUrls
Set well-known deferred properties to String.Empty when not present
Detect duplicate CacheIds
Fixes wixtoolset/issues#4628
Fixes wixtoolset/issues#6405
Fixes wixtoolset/issues#6431
Resolves #272
=> Several fixes in Burn Backend
