wixtoolset/Core

- src/WixToolset.Core/ExtensibilityServices/PreprocessHelper.cs
- src/test/WixToolsetTest.CoreIntegration/PreprocessorFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/Variables/Package.wxs
$(sys.WIXMAJORVERSION)
$(sys.WIXVERSION)
> Add preprocessor variables with WiX version info.

- src/test/WixToolsetTest.CoreIntegration/MsiFixture.cs
- src/test/WixToolsetTest.CoreIntegration/MsiQueryFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/Environment/Environment.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/ErrorsInUI/PackageComponents.wxs
> Add unit tests written during discovery of errors elsewhere

- src/WixToolset.Core.WindowsInstaller/Bind/AddCreateFoldersCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/BindDatabaseCommand.cs
- src/WixToolset.Core/Compiler.cs
- src/test/WixToolsetTest.CoreIntegration/MsiQueryFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/Components/Package.en-us.wxl
- src/test/WixToolsetTest.CoreIntegration/TestData/Components/Package.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Components/PackageComponents.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Components/data/test.txt
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
> Add CreateFolder tuples for null-keypath components in the backend

- src/WixToolset.Core/ExtensibilityServices/CustomActionPlatforms.cs
- src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs
...to simplify creating custom action references following naming conventions.
> Add CreateCustomActionReference method

- WixToolset.Core.sln
- src/test/CompileCoreTestExtensionWixlib/CompileCoreTestExtensionWixlib.csproj
- src/test/CompileCoreTestExtensionWixlib/Program.cs
- src/test/Example.Extension/Data/example.wxs
- src/test/Example.Extension/Example.Extension.csproj
- src/test/Example.Extension/ExampleExtensionData.cs
- src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/SimpleBundle/MultiFileBootstrapperApplication.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/SimpleBundle/MultiFileBundle.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
- src/test/WixToolsetTest.CoreIntegration/WixiplFixture.cs
- src/test/WixToolsetTest.CoreIntegration/WixlibFixture.cs
Update Example.Extension to automatically update based on its Example.wxs.
Use .wixlib instead of .wir, and skip tests which are now failing.
Add more bundle tests.
> Start isolating issue with referencing BA from Bal.wixext

- src/test/Example.Extension/ExampleTableDefinitions.cs
- src/test/Example.Extension/ExampleWindowsInstallerBackendExtension.cs
- src/test/WixToolsetTest.CoreIntegration/MsiQueryFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/EnsureTable/EnsureTable.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
for when it references an extension table with a different name than its tuple.
> Add failing test for EnsureTable

- src/WixToolset.Core.WindowsInstaller/Data/tables.xml
- src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs
- src/test/Example.Extension/Example.Extension.csproj
- src/test/Example.Extension/ExampleTableDefinitions.cs
- src/test/WixToolsetTest.CoreIntegration/ExtensionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/MsiQueryFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/CustomAction/UnscheduledCustomAction.wxs
Update ActionText table definition to set TupleIdIsPrimaryKey to false.
> Implement new IParseHelper methods.

- src/test/Example.Extension/Example.Extension.csproj
- src/test/Example.Extension/ExampleCompilerExtension.cs
- src/test/Example.Extension/ExampleTableDefinitions.cs
- src/test/WixToolsetTest.CoreIntegration/MsiFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadEnsureTable/BadEnsureTable.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Add failing test for the TableDefinition overload of EnsureTable.
> Try to fix build flakiness with Example.Extension

- src/WixToolset.Core.WindowsInstaller/Bind/BindDatabaseCommand.cs
- src/test/WixToolsetTest.CoreIntegration/MsiFixture.cs
Not as useful as intended and I'd rather remove it than potentially have to support something as weird as this.
> Remove partial WixPdb support.

- src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs
- src/WixToolset.Core.Burn/Bundles/ProcessPayloadsCommand.cs
- src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/SingleExeBundle/SingleExePackageGroup.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/SingleExeBundle/SingleExeRemotePayload.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
https://github.com/wixtoolset/Data/pull/46
https://github.com/wixtoolset/Extensibility/pull/28
> Bundle finalize and tests

- src/WixToolset.Core.WindowsInstaller/Bind/BindDatabaseCommand.cs
- src/WixToolset.Core/BindContext.cs
- src/WixToolset.Core/Linker.cs
> Add `IBindContext.SuppressLayout` to suppress cab generation.

- src/WixToolset.Core/Compiler_Bundle.cs
> Don't warn about missing netfx4 switches.

- appveyor.cmd
- src/WixToolset.Core.WindowsInstaller/Bind/AddBackSuppresedSequenceTablesCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/BindDatabaseCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/ExtractMergeModuleFilesCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/GetFileFacadesFromTransforms.cs
- src/WixToolset.Core.WindowsInstaller/Bind/MergeModulesCommand.cs
- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/Compiler_2.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/WixToolset.Core/Linker.cs
- src/test/WixToolsetTest.CoreIntegration/BadInputFixture.cs
> Drive merge process from tuples not rows and fix merge table suppression

- src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs
- src/WixToolset.Core.Burn/Bind/GenerateManifestDataFromIRCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBootstrapperApplicationManifestCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBundleExtensionManifestCommand.cs
- src/WixToolset.Core.Burn/ExtensibilityServices/BurnBackendHelper.cs
- src/WixToolset.Core.Burn/IInternalBurnBackendHelper.cs
- src/WixToolset.Core.Burn/WixToolsetCoreServiceProviderExtensions.cs
- src/test/WixToolsetTest.CoreIntegration/BundleManifestFixture.cs
Add GenerateManifestDataFromIRCommand, which allows the Burn backend to warn on unknown tuples.
https://github.com/wixtoolset/issues/issues/6173
> Implement IBurnBackendHelper and TryAddTupleToDataManifest

- src/WixToolset.Core.Burn/Bind/GenerateManifestDataFromIRCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/CreateOutputFromIRCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/LoadTableDefinitionsCommand.cs
- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/test/Example.Extension/ExampleWindowsInstallerBackendExtension.cs
- src/test/WixToolsetTest.CoreIntegration/BundleManifestFixture.cs
- src/test/WixToolsetTest.CoreIntegration/CustomTableFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BundleCustomTable/BundleCustomTable.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/CustomTable/CustomTable.wxs
https://github.com/wixtoolset/issues/issues/6176
> Implement BundleCustomData. Remove Unreal from CustomTable

- src/WixToolset.Core.Burn/Bind/GenerateManifestDataFromIRCommand.cs
- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BundleCustomTable/BundleCustomTable.wxs
Add more tuples to ignore in GenerateManifestDataFromIRCommand.
> Add BundleCustomDataRef element

- src/test/WixToolsetTest.CoreIntegration/CustomActionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/CustomAction/CustomActionCycle.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
https://github.com/wixtoolset/issues/issues/6201
> Add failing test for CustomAction cycle

- src/WixToolset.Core.WindowsInstaller/Bind/CreateOutputFromIRCommand.cs
- src/WixToolset.Core.WindowsInstaller/Unbind/UnbindDatabaseCommand.cs
- src/WixToolset.Core/Bind/ResolveDelayedFieldsCommand.cs
- src/WixToolset.Core/CommandLine/BuildCommand.cs
- src/WixToolset.Core/CommandLine/CompileCommand.cs
- src/WixToolset.Core/Common.cs
- src/WixToolset.Core/CompileContext.cs
- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/CompilerCore.cs
- src/WixToolset.Core/Compiler_2.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/WixToolset.Core/Compiler_UI.cs
- src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs
- src/WixToolset.Core/ParsedWixVariable.cs
- src/WixToolset.Core/VariableResolver.cs
- src/test/WixToolsetTest.CoreIntegration/CopyFileFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/CopyFile/CopyFile.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Also adds test for https://github.com/wixtoolset/issues/issues/5867
> Compiler performance improvements

- src/test/WixToolsetTest.CoreIntegration/WixlibFixture.cs
https://github.com/wixtoolset/issues/issues/6200
> Create failing test for named bind paths

- src/WixToolset.Core.ExtensionCache/ExtensionCacheManagerCommand.cs
- src/WixToolset.Core.ExtensionCache/ExtensionCacheManagerExtensionCommandLine.cs
- src/WixToolset.Core/CommandLine/CommandLine.cs
- src/WixToolset.Core/CommandLine/CommandLineParser.cs
- src/WixToolset.Core/CommandLine/HelpCommand.cs
- src/WixToolset.Core/CommandLine/VersionCommand.cs
- src/WixToolset.Core/ExtensibilityServices/Messaging.cs
> Display command-line help from Core and extensions

- src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBundleExeCommand.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
https://github.com/wixtoolset/issues/issues/6204
> Generate bundle application manifest in Burn backend

- src/WixToolset.Core.WindowsInstaller/Bind/AddRequiredStandardDirectories.cs
- src/WixToolset.Core.WindowsInstaller/Bind/BindDatabaseCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/BindSummaryInfoCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/CalculateComponentGuids.cs
- src/WixToolset.Core.WindowsInstaller/Bind/SequenceActionsCommand.cs
- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/ExtensibilityServices/PathResolver.cs
- src/WixToolset.Core/Link/ResolveReferencesCommand.cs
- src/WixToolset.Core/Link/SymbolWithSection.cs
- src/WixToolset.Core/Linker.cs
- src/test/WixToolsetTest.CoreIntegration/DirectoryFixture.cs
- src/test/WixToolsetTest.CoreIntegration/MsiQueryFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/CustomAction/SimpleCustomAction.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/CustomTable/CustomTable-Expected.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Directory/Empty.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/ProductWithComponentGroupRef/Product.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Closes wixtoolset/issues#5798 
Closes wixtoolset/issues#5835
> Support implicit standard directory reference and "3264" platform folders

- src/WixToolset.Core.Burn/Bind/SetVariableSearchFacade.cs
- src/WixToolset.Core.Burn/Bundles/CreateBurnManifestCommand.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/test/WixToolsetTest.CoreIntegration/BadInputFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/BundleVariable.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
https://github.com/wixtoolset/issues/issues/4763
> 4763 - Change "string" variable type to literal and add "formatted"

- src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/DuplicateCacheIds.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/DuplicatePayloadNames.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
for https://github.com/wixtoolset/issues/issues/4574 and https://github.com/wixtoolset/issues/issues/4628.
> Add failing tests

- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/Compiler_2.cs
- src/WixToolset.Core/Compiler_Module.cs
- src/WixToolset.Core/Compiler_PatchCreation.cs
https://github.com/wixtoolset/issues/issues/6255
> Obsolete long-deprecated elements and attributes.

- src/WixToolset.Core.Burn/Bundles/OrderPackagesAndRollbackBoundariesCommand.cs
- src/test/WixToolsetTest.CoreIntegration/MsiTransactionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/FirstX64.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/FirstX86.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/SecondX64.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/SecondX86.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/X64AfterX86Bundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/X86AfterX64Bundle.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
https://github.com/wixtoolset/issues/issues/5386
> MSI transaction cleanup

- WixToolset.Core.sln
- appveyor.cmd
- src/CSharp.Build.props
- src/WixToolset.Core.Burn/Bundles/BurnCommon.cs
- src/WixToolset.Core.Burn/WixToolset.Core.Burn.csproj
- src/test/WixToolsetTest.Core.Burn/BurnReaderFixture.cs
- src/test/WixToolsetTest.Core.Burn/WixToolsetTest.Core.Burn.csproj
https://github.com/wixtoolset/issues/issues/6299
> WIXBUG:6299 - Fix OverflowException in ReadUInt32

- src/WixToolset.Core.Burn/Bundles/ProcessPayloadsCommand.cs
- src/WixToolset.Core/ExtensibilityServices/BackendHelper.cs
- src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs
- src/test/WixToolsetTest.CoreIntegration/PayloadFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/Payload/AbsoluteName.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Payload/CanonicalizeName.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Payload/ValidName.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
This is a more user-friendly implementation of https://github.com/wixtoolset/issues/issues/5265.
Also needed for https://github.com/wixtoolset/Bal.wixext/blob/5f00aece054d074fc651e542432f349e3055f582/src/wixext/BalBurnBackendExtension.cs#L80 and https://github.com/wixtoolset/issues/issues/4574.
https://github.com/wixtoolset/Extensibility/pull/47
> Canonicalize Payload/@Name

- src/WixToolset.Core/Compiler_Bundle.cs
- src/test/WixToolsetTest.CoreIntegration/BadInputFixture.cs
- src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
- src/test/WixToolsetTest.CoreIntegration/CustomActionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/RegistryFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/HiddenPersistedBundleVariable.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/UnscheduledPackage.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/UnscheduledRollbackBoundary.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Registry/RegistryKeyEndingWithBackslash.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Also add some failing tests for https://github.com/wixtoolset/issues/issues/4753 and https://github.com/wixtoolset/issues/issues/6291.
Closes https://github.com/wixtoolset/issues/issues/4862.
> 4862 - Disallow Burn Variables that are Hidden and Persisted

- src/WixToolset.Core.Burn/BundleBackend.cs
- src/WixToolset.Core.TestPackage/BundleExtractor.cs
- src/WixToolset.Core.TestPackage/WixRunnerResult.cs
- src/WixToolset.Core.WindowsInstaller/Unbinder.cs
- src/WixToolset.Core.WindowsInstaller/WixToolsetCoreServiceProviderExtensions.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/WixToolset.Core/IUnbinder.cs
- src/test/WixToolsetTest.CoreIntegration/BundleExtractionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BundleWithDetachedContainer/Bundle.wxs
- src/test/WixToolsetTest.CoreIntegration/WixToolsetTest.CoreIntegration.csproj
Rewrite test from @nirbar in https://github.com/wixtoolset/Core/pull/204.
Fix some parsing bugs in bundle compiler.
> Extract bundle test

- src/WixToolset.Core.Burn/Bundles/CreateBundleExeCommand.cs
- src/WixToolset.Core/CommandLine/DecompileCommand.cs
- src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
- src/test/WixToolsetTest.CoreIntegration/CustomTableFixture.cs
- src/test/WixToolsetTest.CoreIntegration/DecompileFixture.cs
Add warning for non-x86 bundles.
https://github.com/wixtoolset/issues/issues/4579
https://github.com/wixtoolset/issues/issues/6180
> Add Bob's test for x64 bundle

- src/WixToolset.Core.WindowsInstaller/Bind/CalculateComponentGuids.cs
- src/WixToolset.Core/CommandLine/BuildCommand.cs
- src/WixToolset.Core/CommandLine/DecompileCommand.cs
- src/test/WixToolsetTest.CoreIntegration/PatchFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchNonSpecific/BundleA/Bundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchNonSpecific/BundleB/Bundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchNonSpecific/BundleC/Bundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchNonSpecific/PackageA/Package.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchNonSpecific/PatchA/Patch.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchNonSpecific/PatchB/Patch.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchNonSpecific/PatchC/Patch.wxs
Fix copy/paste error with ParseWarningAsError.
Fixes https://github.com/wixtoolset/issues/issues/6341.
> Add patch test from old repo and get it passing

- src/WixToolset.Core.WindowsInstaller/Bind/SequenceActionsCommand.cs
- src/test/WixToolsetTest.CoreIntegration/CustomActionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/CustomAction/CustomActionCycleWithTail.wxs
> Checks all custom actions for cycles. Version 3. 

- src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs
- src/test/WixToolsetTest.CoreIntegration/ParseFixture.cs
Fixes https://github.com/wixtoolset/issues/issues/6365
> Don't prefix custom action references.

- src/WixToolset.Core.Burn/Bundles/AutomaticallySlipstreamPatchesCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBootstrapperApplicationManifestCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBundleExtensionManifestCommand.cs
- src/WixToolset.Core.Burn/Bundles/ProcessMsiPackageCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/AssignMediaCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/BindDatabaseCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/CreateCabinetsCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/CreateSpecialPropertiesCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/CreateWindowsInstallerDataFromIRCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/ExtractMergeModuleFilesCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/ProcessDependencyReferencesCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/UpdateFileFacadesCommand.cs
- src/WixToolset.Core.WindowsInstaller/Decompile/Decompiler.cs
- src/WixToolset.Core.WindowsInstaller/ExtensibilityServices/WindowsInstallerBackendHelper.cs
- src/WixToolset.Core/Bind/FileFacade.cs
- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/WixToolset.Core/Compiler_Module.cs
- src/WixToolset.Core/Compiler_Package.cs
- src/WixToolset.Core/Compiler_Patch.cs
- src/WixToolset.Core/Compiler_PatchCreation.cs
- src/WixToolset.Core/Compiler_Tag.cs
- src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs
- src/WixToolset.Core/Link/FindEntrySectionAndLoadSymbolsCommand.cs
- src/WixToolset.Core/Link/ResolveReferencesCommand.cs
- src/WixToolset.Core/Preprocessor.cs
- src/test/WixToolsetTest.CoreIntegration/PreprocessorFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/IncludePath/Package.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/IncludePath/PackageComponents.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/IncludePath/data/DontDoThis.wxi
Resolves wixtoolset/issues#5876
> Fix SourceLineNumbers for Include files and integrate latest changes

- src/WixToolset.Core/ExtensibilityServices/ExtensionManager.cs
Resolves wixtoolset/issues#6184
> Version the extension cache folders

- src/test/WixToolsetTest.CoreIntegration/TestData/WixVariableOverride/Package.en-us.wxl
- src/test/WixToolsetTest.CoreIntegration/TestData/WixVariableOverride/Package.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/WixVariableOverride/PackageComponents.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/WixVariableOverride/data/test.txt
- src/test/WixToolsetTest.CoreIntegration/TestData/WixVariableOverride/data/test2.txt
- src/test/WixToolsetTest.CoreIntegration/WixlibFixture.cs
Created a unit test for WixVariable resolution issue wixtoolset/issues#6376
> Create unit test for WixVariable resolution issue #6376

- src/WixToolset.Core/Linker.cs
- src/test/WixToolsetTest.CoreIntegration/LinkerFixture.cs
Fixes https://github.com/wixtoolset/issues/issues/5886
> Improve missing entry section error message.

- src/WixToolset.Core.Burn/Bundles/ProcessMsiPackageCommand.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/test/WixToolsetTest.CoreIntegration/DependencyExtensionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/PatchFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/Dependency/CustomProviderKeyBundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Dependency/ExePackageProvidesBundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/Dependency/UsingProvidesBundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchFromWixlib/Package.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/PatchFromWixlib/Patch.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/UsingProvides/Package.wxs
Add failing test for patch from MSI that included a file from a wixext.
> Dependency fixes and failing tests

- src/WixToolset.Core/Bind/TransferFilesCommand.cs
- src/WixToolset.Core/CommandLine/BuildCommand.cs
- src/WixToolset.Core/Compiler.cs
- src/WixToolset.Core/CompilerCore.cs
- src/WixToolset.Core/Compiler_EmbeddedUI.cs
- src/WixToolset.Core/Compiler_Package.cs
- src/WixToolset.Core/Compiler_UI.cs
- src/WixToolset.Core/ExtensibilityServices/ParseHelper.cs
- src/WixToolset.Core/LayoutContext.cs
- src/WixToolset.Core/LayoutCreator.cs
- src/WixToolset.Core/WixToolset.Core.csproj
> Centralize disallow inner text handling in ParseHalper

- src/WixToolset.Core.WindowsInstaller/Bind/BindDatabaseCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/CabinetBuilder.cs
- src/WixToolset.Core.WindowsInstaller/Bind/CreateCabinetsCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/GenerateDatabaseCommand.cs
And other minor cleanup.
Fixes wixtoolset/issues#5628
> Default to 1 if NUMBER_OF_PROCESSORS environment variable is invalid

- src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs
- src/WixToolset.Core.Burn/Bind/GenerateManifestDataFromIRCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBootstrapperApplicationManifestCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBundleExtensionManifestCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBurnManifestCommand.cs
- src/WixToolset.Core.Burn/Bundles/GetPackageFacadesCommand.cs
- src/WixToolset.Core.Burn/Bundles/OrderSearchesCommand.cs
- src/WixToolset.Core.Burn/Bundles/ProcessMsiPackageCommand.cs
- src/WixToolset.Core.Burn/Bundles/ProcessPayloadsCommand.cs
- src/WixToolset.Core/Link/ConnectToFeature.cs
- src/WixToolset.Core/Linker.cs
- src/test/WixToolsetTest.CoreIntegration/BundleManifestFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/SharedPayloadsBetweenPackages/SharedPayloadsBetweenPackages.wxs
Plus some minor code cleanup.
Fixes wixtoolset/issues#6370
> Allow payloads to be shared across packages in a Bundle

- src/WixToolset.Core.Burn/Bundles/CreateBootstrapperApplicationManifestCommand.cs
- src/WixToolset.Core/Compiler_Bundle.cs
- src/test/WixToolsetTest.CoreIntegration/BundleManifestFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/CustomPackageDescription/CustomPackageDescription.wxs
Fixes wixtoolset/issues#6371
Fixes wixtoolset/issues#6372
> Correctly set Compressed, Description, DisplayName in BootstrapperApplicationData

- src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs
- src/WixToolset.Core.Burn/Bind/ProcessDependencyProvidersCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateBurnManifestCommand.cs
- src/WixToolset.Core.Burn/Bundles/ProcessMsiPackageCommand.cs
- src/WixToolset.Core.WindowsInstaller/Bind/ProcessDependencyReferencesCommand.cs
- src/WixToolset.Core/Compiler_Dependency.cs
- src/test/WixToolsetTest.CoreIntegration/DependencyExtensionFixture.cs
> Fix dependency providers in a Bundle chain

- src/WixToolset.Core/Bind/ResolveFieldsCommand.cs
- src/test/WixToolsetTest.CoreIntegration/WixlibFixture.cs
> Re-resolve binary .wixlibs with defaulted embedded files

- src/WixToolset.Core.Burn/Bind/BindBundleCommand.cs
- src/WixToolset.Core.Burn/Bundles/CreateNonUXContainers.cs
- src/WixToolset.Core.Burn/Bundles/DetectPayloadCollisionsCommand.cs
- src/WixToolset.Core.Burn/BurnBackendErrors.cs
- src/WixToolset.Core.Burn/BurnBackendWarnings.cs
- src/WixToolset.Core.Burn/WixToolset.Core.Burn.csproj
- src/test/WixToolsetTest.CoreIntegration/BundleFixture.cs
- src/test/WixToolsetTest.CoreIntegration/MsiTransactionFixture.cs
- src/test/WixToolsetTest.CoreIntegration/TestData/BadInput/DuplicatePayloadNames.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/BundleCustomTable/BundleCustomTable.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/X64AfterX86Bundle.wxs
- src/test/WixToolsetTest.CoreIntegration/TestData/MsiTransaction/X86AfterX64Bundle.wxs
Fixes https://github.com/wixtoolset/issues/issues/4574
> Detect payload collisions
